services:
  streamlit_app:
    container_name: streamlit_app
    build: 
      context : .
      dockerfile: ./streamlit_app/Dockerfile
    command: streamlit run streamlit_app/main.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ../:/streamlit_app
    environment:
      - PYTHONUNBUFFERED=1
  api:
    build: 
      context : .
      dockerfile: ./api/Dockerfile
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ../:/api/
    environment:
      - PYTHONUNBUFFERED=1